### ISSUE TITLE
is there any example showing http m3u8 playing code?

### ISSUE THREAD

**Issue by kingctan** [mautilus/sdk#2]
is there any example showing http m3u8 playing code?

**Comment by stenlik** [comment]
Please update latest sources from the git repository. We have updated `PlayerKeyboardInfo` example to show loading hosted media files. To play how HLS stream just update in the `config.js` the `video` parameter. For testing you could use e.g. http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8.

**Comment by kingctan** [comment]
the m3u8 playing only 9s then error out, auto pause, I tried my own server file,also show the same problem. tested on LG emulater.
and on Samsung emulater, it can't play.

**Comment by stenlik** [comment]
We tested the _Apple_ _Bipbopall_ HLS stream on several _Samsung_ _SmartTV_ _Orsay/Tizen_ and _LG_ _NetCast/webOS_ devices and we found video is indeed stopped. It happens, when the video player tries to change the quality. The time stream stops depends on the built-in player buffer size. It could be 10 seconds (one `MPEG-TS` chunk is played) or more. We do not know why so many different TVs have problem with that particular stream – we did not find anything special about it. When we played concrete renditions URLs from the master `.m3u8` URL (e.g. http://devimages.apple.com/iphone/samples/bipbop/gear4/prog_index.m3u8), they were played without any problem, so the issue seems to be the quality switching. In fact we found that technically only the video rendering hangs – on the background the player was continuning with downloading of `MPEG-TS` chunks.

Please check some other test streams from this URL (those we tested, except _Apple_ _Bipbopall_ of course, worked): http://stackoverflow.com/questions/10104301/hls-streaming-video-url-need-for-testing

One more note: Do not use emulators for testing video playback - the support for that is quite limited. 

We will keep you informed if we will find any new information.

**Comment by kingctan** [comment]
@stenlik ok, thanks a lot. I'll try and dive into it.

**Comment by stenlik** [comment]
We tried to investigate the issue with http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8 stream, but it could be different problems on different TVs – one could be that e.g. _Orsay/Tizen_ appears to support officially `MPEG-4 SP/ASP`, while stream is using `MPEG-4 AVC` codec: http://www.samsungdforum.com/Guide/?FolderName=rel00010&FileName=index.html. 

But this does not explain why we saw same problems on e.g. webOS, see: http://developer.lge.com/webOSTV/develop/web-app/webos-tv-platform/supported-media-formats

I personally think that there are certain encoder settings (unknown to me), which when polished will produce the working stream, since the `HLS\MPEG-TS\H.264(AVC)` is far the best supported streaming protocol on connected TVs for ages and this is the only stream, which has such problems.

**Comment by stenlik** [comment]
Dear kingctan, is there anything else we could help with? If not, please close the ticket. Thanks a lot.

**Comment by kingctan** [comment]
Dear @stenlik, Thanks for you help.
I need more test on my device.
Maybe we can close the ticket first.
Thank you.

**Comment by kingctan** [comment]
Hi, I found m3u8 hls stream not work on LG TV and emulator (webos 2.0).
Can you help test this feature?
Thanks.

**Comment by stenlik** [comment]
Please send us the HLS URL.

**Comment by kingctan** [comment]
OK, I have found the key source code about URL check.
and my url not end with "mp4" or "m3u8", which just a GET url, so it can't load the HLS mediaOption.
