### ISSUE TITLE
Found the PlayerKeyboardInfo example mp4 file can't run on samsung smart tv.

### ISSUE THREAD

**Issue by kingctan** [mautilus/sdk#5]
Hi,
I found the PlayerKeyboardInfo example mp4 file can't run on samsung smart tv.
please check it.
Thanks.

**Comment by stenlik** [comment]
Could you provide us more information about what you have done, on which TV and what exactly is not working?
Thanks

**Comment by kingctan** [comment]
ok,
I just clone the code and add PlayerKeyboardInfo example to samsung eclipse and run in emulator,
but the mp4 file not play.
samsung sdk version 5.1.

**Comment by stenlik** [comment]
This is because the video file is part of the package and it does not work in emulator. The example application is prepared to be installed and launched on TV (Note: We are not using emulators at all). How to proceed:
1/ Change video URL in config.js to absolute path where your video file is hosted (something like http://xxx.xxx.xxx.xxx/video.mp4)
2/ Install the widget directly to the Smart TV.

**Comment by stenlik** [comment]
Hello kingctan, is everything working now? Is the issue solved?
